---
- name: Deploy Dev Spaces on OCP
  hosts: localhost
  vars:
    namespce: eclipse-che

  tasks:
    - name: create namespace
      redhat.openshift.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: deploy dev spaces
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: org.eclipse.che/v2
          kind: CheCluster
          metadata:
            name: devspaces
            namespace: "{{ namespace }}"
          spec:
            components:
              cheServer:
                debug: false
                logLevel: INFO
              dashboard: {}
              database:
                credentialsSecretName: postgres-credentials
                externalDb: false
                postgresDb: dbche
                postgresHostName: postgres
                postgresPort: '5432'
                pvc:
                  claimSize: 1Gi
              devWorkspace: {}
              devfileRegistry: {}
              imagePuller:
                enable: false
                spec: {}
              metrics:
                enable: true
              pluginRegistry:
                openVSXURL: 'https://open-vsx.org'
            containerRegistry: {}
            devEnvironments:
              startTimeoutSeconds: 300
              secondsOfRunBeforeIdling: -1
              maxNumberOfWorkspacesPerUser: -1
              containerBuildConfiguration:
                openShiftSecurityContextConstraint: container-build
              disableContainerBuildCapabilities: true
              defaultEditor: che-incubator/che-code/insiders
              defaultComponents:
                - container:
                    image: >-
                      registry.redhat.io/devspaces/udi-rhel8@sha256:aa39ede33bcbda6aa2723d271c79ab8d8fd388c7dfcbc3d4ece745b7e9c84193
                    sourceMapping: /projects
                  name: universal-developer-image
              defaultNamespace:
                autoProvision: true
                template: <username>-devspaces
              secondsOfInactivityBeforeIdling: 1800
              storage:
                pvcStrategy: per-user
            gitServices: {}
            networking:
              auth:
                gateway:
                  configLabels:
                    app: che
                    component: che-gateway-config
